### ISSUE TITLE
Panci doesn't support Tox with variables

### ISSUE THREAD

**Issue by WoLpH** [msabramo/python-panci#13]
Try this tox file for example: https://github.com/WoLpH/django-tags-input/blob/master/tox.ini

Calling panci like this: `panci --to travis tox.ini` I get this output:

```
language: python
python:
- '{.2'
- '{.2'
- '}.-'
- '{.3'
- 3.}
script: '

  pip freeze

  python setup.py test'
```

**Comment by maikhoepfel** [comment]
Just wanted to say thanks for this lovely tool. I would like to see this feature added, but don't have time myself either :(

**Comment by msabramo** [comment]
See https://github.com/msabramo/python-panci/pull/16

Thank you, @maikhoepfel, for the idea of parsing the output of `tox -l`!

**Comment by WoLpH** [comment]
Thanks for the fix @msabramo, I honestly completely forgot about this issue... my bad

**Comment by msabramo** [comment]
@WoLph: No worries. It's my project and any help I get with it is appreciated but not expected!
