### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by karolyi** [msabramo/python-panci#15]
Hey,

great stuff. Still, it misses Python3 support:

```python
  File "/Users/laszlokarolyi/Work/opensource/venv/lib/python3.5/site-packages/panci/toxquickstart.py", line 130
    except ValidationError, err:
```

Any plans on implementing it?

**Comment by msabramo** [comment]
Python 3 has been working for a while; I think I added it shortly after you filed this ticket.
