### ISSUE TITLE
Consider tagging a new release and uploading to PyPI

### ISSUE THREAD

**Issue by mineo** [msabramo/python-panci#17]
Hi Marc,

thanks for this package, it works very well and has made me forget my doubts about the maintainability of .travis.yml in a project using tox :sparkles: 
However, it looks the the package on PyPI is from 2012 and doesn't include the changes from #13. It would be great if you could upload a new version to PyPI, so other people interested in using this great project can easily install a working version. Thanks!

**Comment by ssbarnea** [comment]
PyPI is clearly the official way to release python code, much better than a git repository which can be in an unstable or even unusable state.

**Comment by msabramo** [comment]
Yes, it's been far too long since a release. Just put out https://pypi.python.org/pypi/panci/0.0.1

Thanks, @mineo and @ssbarnea!
