### ISSUE TITLE
conversion from tox.ini to travis.yml is invalid for multiple versions of python

### ISSUE THREAD

**Issue by ssbarnea** [msabramo/python-panci#19]
If you tox.ini file is configured to test two versions of Python, the generated travis.yml file will not work because it does not tell travis which version of python is needed.

This can be easily be seen on https://travis-ci.org/ssbarnea/InfraRed/builds/185545178 where py35 job failed because travis didn't had it installed.

The `.travis.yml` which based on the output from using panci:
```
sudo: false
language: python
cache: pip
env:
  - TOXENV=py27
  - TOXENV=pep8
  - TOXENV=py35
  - TOXENV=ansible-lint
# command to install dependencies
before_script:
  - export PATH=$HOME/.local/bin:$PATH
install:
# if setuptools<17.1 installing even dependencies could fail
- travis_retry pip install --upgrade pip setuptools tox-travis
- travis_retry pip install .
# command to run tests
script:
- pip check
- travis_retry tox
```

Also allow me to thank you for spending time on writing such a time-saver tool. 

If you could also advise on how to manually correct this issue it would be wonderful.

**Comment by mineo** [comment]
As a workaround, you can use `python: 3.5` in your `.travis.yml`, which seems to make the whole thing run on images that support everyything from python 2.6 up to 3.5.
